# Generated by Django 3.2.6 on 2021-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_profile_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offer_letter',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socials',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.IntegerField(null=True),
        ),
    ]
